import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SideNav } from "@/components/sideNav";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isAuthenticated = session?.token;
  return (
    <html lang="en">
      <body className={inter.className}>
        {isAuthenticated && <SideNav />}
        <div className={isAuthenticated ? "body-wrapper" : ""}>{children}</div>
      </body>
    </html>
  );
}
